/*
Información obtenida del sitio web del departamento de sistemas en 2014-12-09
Algunos de los códigos de materia no están publicados todavía,
y por lo tanto quedan en NULL.
*/

INSERT INTO `reservas_disilab`.`subjects` (`name`, `career`, `code`) VALUES

('', 'Homogéneas', NULL),
('', 'Civil', NULL),
('', 'Eléctrica', NULL),
('', 'Electrónica', NULL),
('', 'Industrial', NULL),
('', 'Mecánica', NULL),
('', 'Naval', NULL),
('', 'Química', NULL),


('Química', 'Sistemas de Información', '081420'),
('Sistemas y Organizaciones', 'Sistemas de Información', '082023'),
('Arquitectura de Computadoras', 'Sistemas de Información', '082022'),
('Algoritmos y Estructuras de Datos', 'Sistemas de Información', '082021'),
('Matemática Discreta', 'Sistemas de Información', '082020'),

('Paradigmas de Programación', 'Sistemas de Información', '082026'),
('Sintaxis y Semántica de los Lenguajes', 'Sistemas de Información', '082025'),
('Análisis de Sistemas', 'Sistemas de Información', '082024'),

('Metodología de la Conducción de Equipos de Trabajo', 'Sistemas de Información', '082075'),
('Algoritmos Complejos para Estructuras de Datos Avanzadas', 'Sistemas de Información', NULL),
('Ingeniería de Requisitos', 'Sistemas de Información', NULL),
('Comunicaciones y Redes', 'Sistemas de Información', '082098'),
('Creatividad', 'Sistemas de Información', '082060'),
('Gestión de Recursos Humanos', 'Sistemas de Información', '082061'),
('Innovación Tecnológica', 'Sistemas de Información', '082034'),
('Investigación Tecnológica', 'Sistemas de Información', '082063'),
('Seguridad Informática', 'Sistemas de Información', '082031'),
('Técnicas Avanzadas de Programación', 'Sistemas de Información', '082065'),
('Técnicas de Gráficos por Computadoras', 'Sistemas de Información', '082066'),
('Matemática Superior', 'Sistemas de Información', '082032'),
('Gestión de Datos', 'Sistemas de Información', '082030'),
('Sistemas Operativos', 'Sistemas de Información', '082027'),
('Diseño de Sistemas', 'Sistemas de Información', '082028'),

('Tecnologías Avanzadas en la Construcción de Software', 'Sistemas de Información', '082073'),
('Sistemas de Información Geográfica', 'Sistemas de Información', '082072'),
('Emprendimientos Digitales', 'Sistemas de Información', NULL),
('Informática Industrial', 'Sistemas de Información', NULL),
('Gerenciamiento de Proyectos Informáticos', 'Sistemas de Información', '082074'),
('Criptografía', 'Sistemas de Información', NULL),
('Administración de Personal', 'Sistemas de Información', '082067'),
('Simulación', 'Sistemas de Información', '082041'),
('Investigación Operativa', 'Sistemas de Información', '082034'),
('Redes de Información', 'Sistemas de Información', '082031'),
('Comunicaciones', 'Sistemas de Información', '082029'),
('Teoría de Control', 'Sistemas de Información', '082036'),
('Ingeniería de Software', 'Sistemas de Información', '082038'),
('Administración de Recursos', 'Sistemas de Información', '082033'),

('Infraestructura y Virtualización', 'Sistemas de Información', NULL),
('Inteligencia Artificial Avanzada', 'Sistemas de Información', NULL),
('Tecnologías Avanzadas en Redes', 'Sistemas de Información', '082044'),
('Comunicación y Comercializacion de Productos y Servicios de IT', 'Sistemas de Información', NULL),
('Bioinformática', 'Sistemas de Información', '082045'),
('Desarrollo Emprendedor', 'Sistemas de Información', NULL),
('Implementación de Bases de Datos NoSQL', 'Sistemas de Información', '082042'),
('Inteligencia de Negocios', 'Sistemas de Información', '082080'),
('Tecnología y Discapacidad', 'Sistemas de Información', NULL),
('Marketing en Internet y Nueva Economía', 'Sistemas de Información', NULL),
('Sistemas Avanzados de Bases de Datos', 'Sistemas de Información', NULL),
('Sistemas de Costos y Presupuestos', 'Sistemas de Información', NULL),
('Pericias Informáticas', 'Sistemas de Información', NULL),
('Financiamiento de Proyectos de Internet', 'Sistemas de Información', NULL),
('Gestión del Cambio Organizacional', 'Sistemas de Información', NULL),
('Procesamiento de Señales', 'Sistemas de Información', NULL),
('Arquitectura de Proyectos en TI', 'Sistemas de Información', NULL),
('Modelos de Negocios en Internet', 'Sistemas de Información', NULL),
('Aspectos Legales de las Nuevas TI', 'Sistemas de Información', NULL),
('Modelos Organizacionales', 'Sistemas de Información', NULL),
('Sistemas Mainframe', 'Sistemas de Información', NULL),
('Tecnologías para la Explotación de Información', 'Sistemas de Información', '082092'),
('Sistemas Integrados de Gestión', 'Sistemas de Información', NULL),
('Marcos de Referencia en TI', 'Sistemas de Información', NULL),
('Sistemas de Gestión', 'Sistemas de Información', '082035'),
('Administración Gerencial', 'Sistemas de Información', '082039'),
('Inteligencia Artificial', 'Sistemas de Información', '082040'),
('Proyecto Final', 'Sistemas de Información', '082037'),


('', 'Textil', NULL),
('', 'Otra no especificada', NULL);